app/accounts/urls.py
from django.contrib import admin
from django.urls import path

from django.views.generic import RedirectView
from .views import RegisterView, LoginDefView, LogoutView,TestPermissionView,UploadAvatar

app_name = 'account'
urlpatterns = [
    path('', LoginDefView, name='index'),
    path('register/', RegisterView.as_view(), name='register'),
    path('admin/',RedirectView.as_view(url='/account/'), name='login-redirect'),
    path('profile/',UploadAvatar, name='profile'),
    path('logout/', LogoutView, name='logout'),
    path('test-permission/', TestPermissionView, name='test-permission'),
]

# password admin
# id = rafi pass = saif123
# id = admin pass = Rafi1234
# id = septi pass = rafi1234
# id = saif pass = rafi1234

app/app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# from . import views as main_views
from .views import IndexView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView, name='index'),
    path('account/', include("accounts.urls", namespace='account')),
    path('article/', include("article.urls", namespace='article')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

app/article/urls.py
from django.urls import path
from .views import ArticleIndexView,ArticleAddView

from django.contrib.auth.decorators import login_required



app_name = 'article'
urlpatterns = [
    path('', login_required(ArticleIndexView), name='index'),
    path('add/', login_required(ArticleAddView), name='add'),
]

app/accounts/models.py
from django.db import models
from django.contrib.auth.models import User 
from utils import user_ava_upload_path, upload_media_to_supabase

# Create your models here.
class UserAva(models.Model):
    id_user =  models.ForeignKey(User,models.CASCADE)
    ava = models.ImageField()
    updated_at = models.DateField(null=True)

    def save(self,*args, **kwargs):
        file_path_in_supabase = user_ava_upload_path(self,self.ava.name)

        if self.ava:
            file_data = self.ava.read()
            print(f'change ori name {self.ava.name} to the {file_path_in_supabase}')
            upload_media_to_supabase(file_data ,file_path_in_supabase)
            self.ava.name = file_path_in_supabase

        super().save(*args, **kwargs)

app/article/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone

# Create your models here.

class Article(models.Model):
    judul      = models.CharField(max_length=255)
    content    = models.TextField()
    created    = models.DateTimeField(auto_now_add=True)
    updated    = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    published  = models.DateTimeField(null=True)
    slug       = models.SlugField(blank=True,editable=False)

    class Meta:
        permissions = (
            ("publish_article", "Can publish article"),
        )

    def save(self):
        self.slug = slugify(self.judul)

        if self.is_published == True:
            self.published = timezone.now()
        else:
            self.published = None


        super().save()

app/accounts/views.py
from django.shortcuts import render,redirect
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login,logout
from django.urls import reverse

from django.contrib.auth.models import User
from .form import UploadAvaForm,RegisterUserForm
from django.utils import timezone
from .models import UserAva

# Create your views here.

def LoginDefView(request):
    context = {
        'pageTitle': 'Login Page',
    }

    if request.user.is_authenticated:
        return redirect('index')
    
    if request.method == 'POST':
        username_input = request.POST['username']
        password_input = request.POST['password']

        user = authenticate(request, username=username_input, password=password_input)

        if user is not None:
            login(request, user)
        else:
            return redirect('account:register')
        
        return redirect('index')
    return render(request, 'login/index.html', context)

def LogoutView(request):

    if request.method == 'POST':
        logout(request)
        return redirect('index')

    context = {
        'pageTitle': 'Logout Page',
        'title': 'Logout from Your Account',
        'message': 'Are you sure you want to log out?'
    }
    return render(request, context)

@login_required
def TestPermissionView(request):
    context = {
        'pageTitle': 'Test Permission Page',
        'title': 'Test Your Permissions',
        'message': 'This page is for testing user permissions.'
    }

    return render(request, 'homeAdmin.html', context)

@login_required
def UploadAvatar(request):
    context = {
        'title' : "Upload File",
        'user' : request.user,
        'form' : UploadAvaForm
    }

    if request.method == 'POST':
        form = UploadAvaForm(request.POST, request.FILES)
        if form.is_valid():
            user_ava = form.save(commit=False)
            user_ava.id_user = request.user  # set the user manually
            user_ava.updated_at = timezone.now()
            user_ava.save()
            return redirect('index')
    else:
        form = UploadAvaForm()

    return render(request,'account/profile.html',context)


class RegisterView(CreateView):
    model = User
    template_name = 'login/register.html'
    form_class = RegisterUserForm
    
    def form_valid(self, form):
        # Modify the user object before saving
        user = form.save(commit=False)
        user.is_active = True
        user.set_password(form.cleaned_data['password'])
        user.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('account:index')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pageTitle'] = 'Register Page'
        context['title'] = 'Create a New Account'
        context['message'] = 'Fill in the form below to create a new account.'
        
        return context

app/app/views.py
from django.views.generic import TemplateView
from django.shortcuts import render,redirect
from accounts.models import UserAva # model UserAva
from utils import get_avatar_url
from django.conf import settings


def IndexView(request):
    template_name = None
    
    context = {
        'pageTitle': 'Home Page',
        'title': 'Welcome to My Docker-app',
        'message': 'This is a simple docker app with Django',
    }

    if request.user.is_authenticated:
        template_name = 'homeAuth.html'
        context['page'] = 'Authenticated'
        context['user'] = request.user.username

        try:
            user_ava = UserAva.objects.get(id_user=request.user)
        except UserAva.DoesNotExist:
            user_ava = None

        if request.user and user_ava:
            context['profilePicture'] = get_avatar_url(user_ava.ava,settings.SUPABASE_BUCKET)

    else:
        template_name = 'index.html'
        context['page'] = 'Home unauthenticated'
        context['user'] = None

    return render(request, template_name, context)

app/article/views.py
import os
from django.shortcuts import render
from django.urls import resolve
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import user_passes_test, permission_required

# Create your views here.

def ArticleIndexView(request):
    context = {
        'pageTitle': 'Article Index',
        'title': 'Articles',
        'message': 'This is the index page for articles.'
    }

    print("there is a group : ", Group.objects.all())
    print("this user : ", request.user," is in groups : ", request.user.groups.all())


    
    return render(request, 'article/index.html', context)

@permission_required('article.delete_article')
def ArticleAddView(request):

    current_path = request.path
    path_parts = current_path.strip("/").split("/")
    path_link = []
    stringTemp = ""

    for i,item in enumerate(path_parts):    
        
        if i == 0:
            stringTemp += f"{item}:index"
            path_link.append(stringTemp)
            stringTemp = f"{item}:"
        else :
            stringTemp += f"{item}"
            path_link.append(stringTemp)


    path_name_link = zip(path_parts,path_link)
    
    context = {
        "pageTitle" : "add Article",
        "path_exploded" : path_name_link,
        # "path_exploded" : 
    }

    return render(request,'article/addArticle.html',context)

app/accounts/templates/login/index.html
{% extends "base.html" %} {% block placeContent %}
{% include "navbar/navbar-public.html" %}

<div class="container-md w-25 mt-5">

    <form method='POST'>
      {% csrf_token %}
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Email or Username</label>
        <input
          type="text"
          class="form-control"
          name="username"
          id="exampleInputEmail1"
          aria-describedby="emailHelp"
        />
        <div id="emailHelp" class="form-text">
          We'll never share your email with anyone else.
        </div>
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" name="password" class="form-control" id="exampleInputPassword1" />
      </div>
      <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1" />
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
      </div>
      <button type="submit" class="btn btn-primary">Login</button>
    </form>

    <p><a class="fs-6" href={% url 'account:register' %}>dont have an account?</a></p>
        
</div>
{% endblock placeContent %}

app/accounts/templates/login/register.html
{% extends "base.html" %}

{% block placeContent %}
{% include "navbar/navbar-public.html" %} 
<h1 class="d-flex justify-content-center">Register</h1>
<div class="container-md w-25 mt-5">
  
  <form method='POST'>
      {% csrf_token %}
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Email address</label>
        <input
          type="email"
          name="email"
          class="form-control"
          id="exampleInputEmail1"
          aria-describedby="emailHelp"
          placeholder="Enter your email"
        />
        <div id="emailHelp" class="form-text">
          We'll never share your email with anyone else.
        </div>
      </div>
      <div class="mb-3">
        <label for="inputUsername" class="form-label">Username</label>
        <input type="text" name="username" class="form-control" id="inputUsername" placeholder="Enter your username" />
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Enter your password" />
      </div>
      <button type="submit" class="btn btn-primary">Register</button>
    </form>

</div>

{% endblock placeContent %}

app/article/templates/article/addArticle.html
{% extends "base.html" %}

{% block placeContent %}
{% include "navbar/navbar-auth.html" %}

    <div class="container">
        {% for name, link in path_exploded  %}
        
            <span><a href={% url link %}>{{ name }}</a></span>
            {% if not forloop.last%}
            <span>&raquo</span>
            {% endif %}
        
        {% endfor %}

        <h1>{{ pageTitle }}</h1>
    </div>
{% endblock placeContent %}

app/article/templates/article/index.html
{% extends "base.html" %}
{% block placeContent %}
{% include "navbar/navbar-auth.html" %}

<div class="container">
    <span><a href={% url "article:add" %}>add Article</a></span>
    <h1>Tes Article Page</h1>
</div>
{% endblock placeContent %}

app/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block customCss %}{% endblock customCss %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript%}
    <title>{{pageTitle}}</title>
    {% load livereload_tags %}
    
</head>
<body>
    {% block placeContent  %}

    {% endblock placeContent  %}
    {% block customJs %}
    
    {% endblock customJs %}
    {% livereload_script %}
</body>
</html>

app/templates/homeAdmin.html
{% extends "base.html" %}

{% block placeContent %}
{% include "navbar/navbar-auth.html" %}
    <div class="section1 position-absolute start-0 px-5" style="top: 25%;">
        <h1>Welcome Admin {{ page }}</h1>
        <p>Helo Admin {{ user }} !</p>
    </div>
{% endblock %}

app/templates/homeAuth.html
{% extends "base.html" %}
{% load static %}

{% block placeContent %}
{% include "navbar/navbar-auth.html" %}
    <div class="section1 position-absolute start-0 px-5" style="top: 25%;">
        <h1>Welcome in{{ page }}</h1>
        <p>Helo {{ user }} !</p>

        {% if profilePicture %}
        <img src="{{ profilePicture }}" alt="">
        {% else %}
        <img src="{% static 'img/defaultPfp.png' %}" alt="">
        {% endif %}


        <p><a href={% url "article:add" %}>Delete Article?</a></p>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block placeContent %}
{% include "navbar/navbar-public.html" %}
    <div class="section1 position-absolute start-0 px-5" style="top: 25%;">
        <h1>{{ title }}</h1>
        <p>{{ message }}</p>
    </div>
{% endblock %}

app/templates/navbar/navbar-auth.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Hi! {{  user }}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav position-absolute top-0 end-0 me-3">
        <li class="nav-item my-2">
          <a class="nav-link active" aria-current="page" href={% url "index" %}>Home</a>
        </li>
        <li class="nav-item my-2 mx-2">
          <a class="nav-link border border-primary rounded bg-primary text-white" href={% url "account:profile" %}>profile</a>
        </li>
        <li class="nav-item my-2 mx-2">
          <a class="nav-link border border-primary rounded bg-primary text-white" href={% url "article:index" %}>article</a>
        </li>
        <li class="nav-item my-2 mx-2">
          <form method="POST" action="{% url 'account:logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-link nav-link text-decoration-none text-white bg-danger mx-2">Logout</button>
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/navbar/navbar-public.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Testing User Authentication</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav position-absolute top-0 end-0 me-3">
        <li class="nav-item my-2">
          <a class="nav-link active" aria-current="page" href={% url 'index' %}>Home</a>
        </li>
        <li class="nav-item my-2">
          <a class="nav-link border border-primary rounded bg-primary text-white" href={% url 'account:index' %}>Login</a>
        </li>
      </ul>
    </div>
  </div>
</nav>